name: metrics-sample
version: '0.1.0.0'
category: Web
author: David Overton
maintainer: doverton@seek.com.au
copyright: 2020 David Overton
license: BSD3
github: dmoverton/metrics-sample
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5
  - aeson
  - servant-server
  - servant-websockets
  - text
  - wai
  - warp
  - websockets
executables:
  metrics-sample-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - metrics-sample
tests:
  metrics-sample-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - metrics-sample
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
